PAYARA-3992 JSON-B Serialisation Error With Custom Serialiser
payara/patched-src-yasson pull request #4
Opened 2019-08-02 16:24 UTC by MattGill98

I've given the user serialiser a fallback serialiser, so that instead of throwing an exception it falls back to that. Seems to work okay for recursive objects as well as the customer use case.

2019-08-02 16:32 UTC, MattGill98 commented
Sorry for the mess, had an absolute mare with GPG keys

2019-08-05 10:56 UTC, pdudits requested changes
I like how this works, but we're going to territory which is not covered by the spec. 

So we'd need to check if there is at least de-facto agreement on how this should work (i. e. by checking what johnzon does), and proposing a spec change. In the meantime, this should be flagged as experimental/vendor feature i. e. by custom property in the config.

2019-08-05 10:56 UTC, pdudits commented on src/main/java/org/eclipse/yasson/internal/model/PropertyModel.java
> + * All rights reserved.
I believe the correct copyright is adding a line
```
Copyright (c) 2019 Payara Foundation and/or its affiliates. All rights reserved
```

2019-08-05 14:24 UTC, jGauravGupta approved these changes

2019-08-05 14:51 UTC, Pandrex247 commented on src/main/java/org/eclipse/yasson/internal/model/PropertyModel.java
> + * All rights reserved.
I'm not convinced myself, I think the way Matt has done it is correct.
Note: I'm not a copyright expert.

2019-08-05 14:51 UTC, Pandrex247 commented on src/main/java/org/eclipse/yasson/internal/model/PropertyModel.java
> + * All rights reserved.
Well, barring the fact it should be Payara Foundation rather than Payara Services

2019-08-05 15:59 UTC, MattGill98 commented on src/main/java/org/eclipse/yasson/internal/model/PropertyModel.java
> + * All rights reserved.
I don't know what you're talking about 🧐

2019-08-07 08:37 UTC, MattGill98 commented
@pdudits as soon as this has your approval I'll merge both this and the main PR!

2019-08-08 09:13 UTC, Pandrex247 commented
@MattGill98 not without updating the patched project PR please :)

2019-08-08 09:38 UTC, pdudits approved these changes

2019-08-08 13:56 UTC, merged